# Generated by Django 3.1.1 on 2020-10-12 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_remove_product_homedelivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='home_delivery',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
