# Generated by Django 3.1.1 on 2020-10-12 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_order_home_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='home_delivery',
            field=models.BooleanField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default=True, null=True),
        ),
    ]
