# Generated by Django 3.1.1 on 2020-10-12 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_auto_20201012_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='home_delivery',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=200, null=True),
        ),
    ]
